
- name: Converge
  hosts: all
  roles:
  - desktop_env

  vars:
    pkgs:
      - i3
      - i3status
      - i3lock
      - picom
      - dunst

  tasks:
    - name: Check if everythign is installed
      apt:
       name: "{{ item }}"
       state: present
      loop: "{{ pkgs }}"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600

    - name: Update apt cache.
      apt:
        name: git
        state: present

