namespace: dnfreddie
name: sysops
version: 1.0.0
readme: README.md
authors:
  - DnFreddie
description: Collection of my personal role for sysops toll
license:
  - MIT
license_file: './LICENSE'
tags: []
dependencies: {}
repository: https://github.com/DnFreddie/ansible-sysops-collection
documentation: https://github.com/DnFreddie/ansible-sysops-collection
homepage: https://github.com/DnFreddie/ansible-sysops-collection
issues: https://github.com/DnFreddie/ansible-sysops-collection
build_ignore: []
