---
url: "https://api.github.com/repos/prometheus/node_exporter/releases/latest
"
config: 
  file: "/etc/sysconfig/node_exporter"
  templ: "node_exporter.j2"
  service_templ: "node_exporter.service.j2"
dir: 
  install: "/opt/node_exporter"
  data: "/var/lib/node_exporter/textfile_collector"
node_port: 9100
update: false

