- name: Create a Podman volume
  containers.podman.podman_volume:
    name: linkding_data
    state: present

- name: Start the linkding container 
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: "docker.io/sissbruecker/linkding:latest"
    state: started
    env: "{{ env_vars | items2dict }}"
    env_file: "{{ role_path }}/files/env"
    ports:
      - "{{ container_port }}:{{ container_port }}"
    volumes:
      - "linkding_data:/etc/linkding/data:Z"  

- name: Check if the systemd service already exists
  stat:
    path: "{{ ansible_env.HOME }}/.config/systemd/user/container-{{ container_name }}.service"
  register: exist

- block:
    - name: Create user service directory
      file: 
        path: "{{ ansible_env.HOME }}/.config/systemd/user/"
        state: directory
        mode: '0755'

    - name: Create systemd user service
      containers.podman.podman_generate_systemd:
        name: "{{ container_name }}"
        dest: "{{ ansible_env.HOME }}/.config/systemd/user/"
  when: not exist.stat.exists

- name: Reload the systemd daemon
  ansible.builtin.systemd:
    name: "container-{{ container_name }}"
    scope: user
    daemon_reload: true
    state: started
    enabled: true

- name: The linkding has been successfully installed
  debug:
    msg:
      - "The installation of linkding has been successful. Check out http://localhost:{{ container_port }}/"

