- name: Download or update Node_exporter
  ansible.builtin.include_tasks: download_release.yml
- name: Setup Node_exporter
  block:
    - name: Create a group for Node_exporter
      ansible.builtin.group:
        name: node_exporter
        system: yes
    - name: Make a user for Node_exporter
      ansible.builtin.user:
        name: node_exporter
        shell: /sbin/nologin
        system: yes
        create_home: no
        group: node_exporter
    - name: Create Node_exporter directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: node_exporter
        group: node_exporter
        mode: "0755"
      loop: "{{ dir.values() }}"

- name: Configure Node_exporter
  block:
    - name: Ensure the directory for the configuration file exists
      ansible.builtin.file:
        path: "{{ config.file | dirname }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Copy the configuration file
      ansible.builtin.template:
        src: "{{ config.templ}}"
        dest: "{{ config.file }}"
        owner: node_exporter
        group: node_exporter
        mode: "0640"
    - name: Open firewall for Node_exporter (port {{ node_port }})
      ansible.builtin.firewalld:
        port: "{{ node_port }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
      failed_when: false
    - name: Copy Node_exporter service file
      ansible.builtin.template:
        src: "{{ config.service_templ}}"
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode: "0644"
  notify: node_restart
  when: not update | bool
