---
- name: Setup repositories on Rocky Linux 9
  block:
    - name: Install EPEL repository
      ansible.builtin.yum:
        name: epel-release
        state: present

    - name: Enable PowerTools repository (crb)
      ansible.builtin.yum:
        name: dnf-plugins-core
        state: present

    - name: Enable CRB (PowerTools) repository
      ansible.builtin.command:
        cmd: dnf config-manager --set-enabled crb

    - name: Install the 'Development tools' package group
      ansible.builtin.dnf:
        name: "@Development tools"
        state: present

    - name: Install the 'Development tools' package group
      ansible.builtin.dnf:
        name: "@Container Management"
        state: present


    - name: Ensure all installed repositories are enabled and up-to-date
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_cache: yes

  when: 
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution'] == 'Rocky'
    - ansible_facts['distribution_major_version'] == '9'
    - ansible_facts['pkg_mgr'] == 'dnf'

