galaxy_info:
  author: DnFreddie
  description: Prometheus role for Ansible
  company: optional

  license: MIT

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: RedHat
      versions:
        - 8
        - 9

  galaxy_tags:
    - monitoring
    - prometheus
    - observability
    - metrics
    - linux
    - systemd

dependencies: []

