- name: Download or update Prometheus
  ansible.builtin.include_tasks: download_release.yml
- name: Setup Prometheus
  block:
    - name: Create a group for Prometheus
      ansible.builtin.group:
        name: prometheus
        system: yes
    - name: Make a user for Prometheus
      ansible.builtin.user:
        name: prometheus
        shell: /sbin/nologin
        system: yes
        create_home: no
        group: prometheus
    - name: Create Prometheus directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: "0755"
      loop: "{{ dir.values() }}"

- name: Configure Prometheus
  block:
    - name: Ensure the directory for the configuration file exists
      ansible.builtin.file:
        path: "{{ config.file | dirname }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Copy the configuration file
      ansible.builtin.template:
        src: "{{ config.templ }}"
        dest: "{{ config.file }}"
        owner: prometheus
        group: prometheus
        mode: "0640"
    - name: Open firewall for Prometheus (port {{ prom_port }})
      ansible.builtin.firewalld:
        port: "{{ prom_port }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
      failed_when: false
    - name: Copy Prometheus service file
      ansible.builtin.template:
        src: "{{ config.service_templ}}"
        dest: /etc/systemd/system/prometheus.service
        owner: root
        group: root
        mode: "0644"
  notify: prometheus_restart
  when: not update | bool

