
---
- name: Setup repositories on Rocky Linux 9 
  block:
    - name: Check if the OS is Rocky Linux 9 and DNF is present
      ansible.builtin.fail:
        msg: "This playbook is designed only for Rocky Linux 9 with DNF."
      when: not (ansible_facts['os_family'] == 'RedHat' and 
                 ansible_facts['distribution'] == 'Rocky' and 
                 ansible_facts['distribution_major_version'] == '9' and 
                 ansible_facts['pkg_mgr'] == 'dnf')

    - name: Install EPEL repository
      ansible.builtin.yum:
        name: epel-release
        state: present

    - name: Enable PowerTools repository (crb)
      ansible.builtin.yum:
        name: dnf-plugins-core
        state: present

    - name: Enable CRB (PowerTools) repository
      ansible.builtin.command: dnf config-manager --set-enabled crb

      

    - name: Ensure all installed repositories are enabled and up-to-date
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_cache: yes

  become: true

