url: "https://api.github.com/repos/prometheus/prometheus/releases/latest"
config:
  file: "/etc/prometheus.yml"
  templ: prometheus.yml.j2
  service_templ: prometheus.service.j2

dir:
  install: "/opt/prometheus"
  data: "/opt/prometheus/data"
prom_port: 9090 
update: false
