server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

  - targets:
      - localhost
    labels:
      job: audit
      __path__: /var/log/audit/audit.lo*

  - targets:
      - localhost
    labels:
      job: selinux
      __path__: /var/log/messages*


